# Generated by Django 6.0.2 on 2026-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='myapp.specialty'),
        ),
    ]
