# Generated by Django 5.2.12 on 2026-03-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hospital_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
