# Generated by Django 6.0.2 on 2026-03-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_doctor_specialties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='location',
        ),
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
