# Generated by Django 6.0.2 on 2026-03-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_hospital_location_hospital_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='about',
            field=models.TextField(blank=True, help_text='A general description or overview of the hospital.', null=True),
        ),
    ]
