# Generated by Django 5.2.12 on 2026-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_department_hospital_index_status_alter_hospital_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
