# Generated by Django 5.2.12 on 2026-03-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_department_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='departments/logos/'),
        ),
    ]
