# Generated by Django 6.0.2 on 2026-03-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_review_options_alter_doctor_hospital_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='DoctorReview',
        ),
    ]
