# Generated by Django 6.0.2 on 2026-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier for the hospital.', max_length=255, null=True, unique=True),
        ),
    ]
