# Generated by Django 6.0.2 on 2026-03-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_hospital_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier for the hospital.', max_length=255, unique=True),
        ),
    ]
