# Generated by Django 6.0.2 on 2026-03-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_hospital_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('bmdc_registration_number', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('current_workplace', models.CharField(max_length=200)),
                ('current_designation', models.CharField(blank=True, max_length=200)),
                ('previous_workplace', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Check this box after you have verified and created a Doctor profile.')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
