# Generated by Django 6.0.2 on 2026-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_doctorsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsubmission',
            name='location',
            field=models.CharField(default='', help_text='e.g., Mirpur, Dhaka', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorsubmission',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_submissions/'),
        ),
        migrations.AddField(
            model_name='doctorsubmission',
            name='years_of_practice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
